#!/usr/bin/env bash

# Shared GPU sweep defaults for the final CPU/GPU compaction speedup runs.
FINAL_SPEEDUP_GPU_DEFAULT_VALUE_SIZES="${FINAL_SPEEDUP_GPU_DEFAULT_VALUE_SIZES:-32 64 128 256 512 1024}"
FINAL_SPEEDUP_GPU_DEFAULT_MODES="${FINAL_SPEEDUP_GPU_DEFAULT_MODES:-q_paper_with_plan q_paper_without_plan c_paper_with_plan c_paper_without_plan}"
FINAL_SPEEDUP_GPU_DEFAULT_RUNS="${FINAL_SPEEDUP_GPU_DEFAULT_RUNS:-5}"
FINAL_SPEEDUP_GPU_DEFAULT_ZIPF_ALPHA="${FINAL_SPEEDUP_GPU_DEFAULT_ZIPF_ALPHA:-0.0}"
FINAL_SPEEDUP_GPU_DEFAULT_USER_KEY_SPACE="${FINAL_SPEEDUP_GPU_DEFAULT_USER_KEY_SPACE:-200000000}"
FINAL_SPEEDUP_GPU_DEFAULT_GRAPH_DIR="${FINAL_SPEEDUP_GPU_DEFAULT_GRAPH_DIR:-./graphs/final_speedup}"
